concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
env:
  ANDROID_EMU_NAME: test
  ANDROID_EMU_TARGET: default
  ANDROID_SDK_VERSION: '28'
  IOS_DEVICE_NAME: iPhone 12
  IOS_PLATFORM_VERSION: '16.2'
  XCODE_VERSION: '14.2'
jobs:
  build:
    name: JDK ${{ matrix.java }} - ${{ matrix.platform }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Gradle
      run: "latest_snapshot=$(curl -sf https://oss.sonatype.org/content/repositories/snapshots/org/seleniumhq/selenium/selenium-api/\
        \ | \\\n  python -c \"import sys,re; print(re.findall(r'\\d+\\.\\d+\\.\\d+-SNAPSHOT',\
        \ sys.stdin.read())[-1])\")\necho \">>> $latest_snapshot\"\necho \"latest_snapshot=$latest_snapshot\"\
        \ >> \"$GITHUB_ENV\"\n./gradlew clean build -PisCI -Pselenium.version=$latest_snapshot\n"
    - continue-on-error: true
      if: matrix.e2e-tests == 'android' ||  matrix.e2e-tests == 'ios'
      name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - continue-on-error: true
      if: matrix.e2e-tests == 'android' ||  matrix.e2e-tests == 'ios'
      name: Install Appium
      run: npm install --location=global appium
    - continue-on-error: true
      if: matrix.e2e-tests == 'android'
      name: Install UIA2 driver
      run: appium driver install uiautomator2
    - continue-on-error: true
      if: matrix.e2e-tests == 'android'
      name: Run Android E2E tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ env.ANDROID_SDK_VERSION }}
        avd-name: ${{ env.ANDROID_EMU_NAME }}
        disable-spellchecker: true
        script: ./gradlew e2eAndroidTest -PisCI -Pselenium.version=$latest_snapshot
        sdcard-path-or-size: 1500M
        target: ${{ env.ANDROID_EMU_TARGET }}
    - continue-on-error: true
      if: matrix.e2e-tests == 'ios'
      name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
    - continue-on-error: true
      if: matrix.e2e-tests == 'ios'
      name: Install XCUITest driver
      run: appium driver install xcuitest
    - continue-on-error: true
      if: matrix.e2e-tests == 'ios'
      name: Prebuild XCUITest driver
      run: appium driver run xcuitest build-wda
    - continue-on-error: true
      if: matrix.e2e-tests == 'ios'
      name: Prepare iOS simulator
      run: 'xcrun simctl list

        target_sim_id=$(xcrun simctl list devices available | grep "$IOS_DEVICE_NAME
        (" | cut -d "(" -f2 | cut -d ")" -f1)

        open -Fn "/Applications/Xcode_$XCODE_VERSION.app/Contents/Developer/Applications/Simulator.app"

        xcrun simctl bootstatus $target_sim_id -b

        '
    - continue-on-error: true
      if: matrix.e2e-tests == 'ios'
      name: Run iOS E2E tests
      run: ./gradlew e2eIosTest -PisCI -Pselenium.version=$latest_snapshot
    strategy:
      fail-fast: false
      matrix:
        include:
        - e2e-tests: ios
          java: 11
          platform: macos-12
        - e2e-tests: android
          java: 17
          platform: macos-latest
        - java: 21
          platform: ubuntu-latest
name: Appium Java Client CI
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
